
services:
  react-app:
    build: ui
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
    env_file:
      - .env

  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3406:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: amila_one
      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: Amila_Rpw
networks:
  springapimysql-net: