
CREATE TABLE IF NOT EXISTS `make` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `code` varchar(55) NOT NULL DEFAULT '',
  `title` varchar(55) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=72 ;
